import { TinaModuleFetch } from '@tinacms/auth';

export default {
  clientId: 'YOUR_CLIENT_ID', // هتحتاج تسجل في tina.io وتاخد clientId (مجاني).
  branch: 'main',
  token: 'YOUR_TOKEN', // من tina.io.
  build: {
    outputFolder: "admin",
    publicFolder: "",
  },
  media: {
    tina: {
      mediaRoot: "images/blog",
      publicFolder: "",
    },
  },
  schema: {
    collections: [
      {
        name: "blog",
        label: "المدونة القانونية",
        path: "blog",
        fields: [
          {
            type: "string",
            name: "title",
            label: "العنوان",
          },
          {
            type: "datetime",
            name: "date",
            label: "تاريخ النشر",
          },
          {
            type: "image",
            name: "image",
            label: "صورة بارزة",
          },
          {
            type: "string",
            name: "description",
            label: "وصف قصير",
            ui: { component: "textarea" },
          },
          {
            type: "rich-text",
            name: "body",
            label: "المحتوى",
            isBody: true,
          },
        ],
      },
    ],
  },
};
